# PostgreSQL Configuration
db.url=jdbc:postgresql://localhost:5433/healthcenter_db
db.username=postgres
db.password=1234
db.driver=org.postgresql.Driver

# Hibernate Config
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
